<a href="https://colab.research.google.com/github/DataCrusade1999/expert-winner/blob/main/Sentiment_Analysis_With_Scikit.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1511]:
import io
import pickle
import numpy as np
import pandas as pd
import datetime
from google.colab import files
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
from sklearn.naive_bayes import GaussianNB
from sklearn import svm
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import f1_score

**LOADING DATA**

In [1457]:
url='https://raw.githubusercontent.com/DataCrusade1999/Python/master/Data/Books_small_10000.csv'

In [1458]:
Books_small=pd.read_csv(url)
Books_small.head()

reviewerID        asin  ... unixReviewTime   reviewTime
0  A1F2H80A1ZNN1N  B00GDM3NQC  ...     1390435200  01 23, 2014
1   AI3DRTKCSK4KX  B00A5MREAM  ...     1399593600   05 9, 2014
2  A3KAKFHY9DAC8A  0446547573  ...     1404518400   07 5, 2014
3   ATYBCYD6BIXVL  0955809215  ...     1389225600   01 9, 2014
4  A17K95SEU3J68U  0991500776  ...     1404864000   07 9, 2014

[5 rows x 10 columns]

**PERFORMING EDA**

**In the first case below, we say "give us the values of the rows with index from 0 to 999 (inclusive) and columns labeled from "reviewText" to "overall" (inclusive)". In the second case, we say "give us the values of all the rows in the columns 5 to 7" (as in a typical Python slice: the maximal value is not included).**

In [1459]:
Books_small.loc[0:,'reviewText':'overall']

reviewText  overall
0     I bought both boxed sets, books 1-5.  Really a...        5
1     I enjoyed this short book. But it was way way ...        3
2     I love Nicholas Sparks. I&#8217;ve read everyt...        4
3     I really enjoyed this adventure and look forwa...        4
4     It was a decent read.. typical story line. Not...        3
...                                                 ...      ...
9995  The whole series was great!  Melody is a fanta...        5
9996  I didn't thing that much of this book.  I am a...        3
9997  It is an emotional TRIP to the past with Trip ...        5
9998  This definitely got under my veins whereby I h...        5
9999  Highly recommend this entire trilogy. It is ve...        4

[10000 rows x 2 columns]

In [1460]:
Books_small.iloc[0:,5:7]

reviewText  overall
0     I bought both boxed sets, books 1-5.  Really a...        5
1     I enjoyed this short book. But it was way way ...        3
2     I love Nicholas Sparks. I&#8217;ve read everyt...        4
3     I really enjoyed this adventure and look forwa...        4
4     It was a decent read.. typical story line. Not...        3
...                                                 ...      ...
9995  The whole series was great!  Melody is a fanta...        5
9996  I didn't thing that much of this book.  I am a...        3
9997  It is an emotional TRIP to the past with Trip ...        5
9998  This definitely got under my veins whereby I h...        5
9999  Highly recommend this entire trilogy. It is ve...        4

[10000 rows x 2 columns]

In [1461]:
Books_small.shape

(10000, 10)

In [1462]:
Books_small['overall'].value_counts() #<---Gives Us Number Of Occurences Of A Particular Value in Digits

5    5930
4    2448
3     978
2     375
1     269
Name: overall, dtype: int64

In [1463]:
Books_small['overall'].value_counts(normalize=True)  #<---Gives Us Number Of Occurences Of A Particular Value in Fractions

5    0.5930
4    0.2448
3    0.0978
2    0.0375
1    0.0269
Name: overall, dtype: float64

In [1464]:
Books_small.sort_values(by='overall', ascending=False).head() #<--Starts From Big And Goes Down

reviewerID        asin  ... unixReviewTime   reviewTime
0     A1F2H80A1ZNN1N  B00GDM3NQC  ...     1390435200  01 23, 2014
5801  A1TZTFYEOPR4CO  1250037220  ...     1402617600  06 13, 2014
5797   AFE0AGQT50MBJ  1449417094  ...     1396828800   04 7, 2014
5795  A2H0KFB0IUNRT7  B005REXCKE  ...     1393545600  02 28, 2014
5794   A2YJ8VP1SSHJ7  B007YN8IGE  ...     1391040000  01 30, 2014

[5 rows x 10 columns]

In [1465]:
Books_small.sort_values(by='overall', ascending=True).head() #<--Starts From Low And Goes Up

reviewerID        asin  ... unixReviewTime   reviewTime
3419   AQY5XBYSENNZQ  1250006082  ...     1400544000  05 20, 2014
8649  A2PWDBZQPR9JU6  0399161465  ...     1398297600  04 24, 2014
2730   A9FIEIKKPTX89  B00HOHMIVQ  ...     1392076800  02 11, 2014
1595   AKJEYA96I1QE6  0764204319  ...     1390694400  01 26, 2014
2731  A3LUUNZVGSSA3M  0446517321  ...     1400457600  05 19, 2014

[5 rows x 10 columns]

In [1466]:
Books_small.describe()

helpful/0     helpful/1       overall  unixReviewTime
count  10000.000000  10000.000000  10000.000000    1.000000e+04
mean       0.583800      0.797400      4.339500    1.396855e+09
std        2.156396      3.163219      0.983736    4.931959e+06
min        0.000000      0.000000      1.000000    1.388534e+09
25%        0.000000      0.000000      4.000000    1.392509e+09
50%        0.000000      0.000000      5.000000    1.396915e+09
75%        1.000000      1.000000      5.000000    1.401062e+09
max      100.000000    154.000000      5.000000    1.406074e+09

In [1467]:
Books_small.head()

reviewerID        asin  ... unixReviewTime   reviewTime
0  A1F2H80A1ZNN1N  B00GDM3NQC  ...     1390435200  01 23, 2014
1   AI3DRTKCSK4KX  B00A5MREAM  ...     1399593600   05 9, 2014
2  A3KAKFHY9DAC8A  0446547573  ...     1404518400   07 5, 2014
3   ATYBCYD6BIXVL  0955809215  ...     1389225600   01 9, 2014
4  A17K95SEU3J68U  0991500776  ...     1404864000   07 9, 2014

[5 rows x 10 columns]

In [1468]:
Books_small.tail()

reviewerID        asin  ... unixReviewTime   reviewTime
9995  A32FV8MF6KTRYE  0615676863  ...     1389830400  01 16, 2014
9996  A2IYZ41783TX4R  B00GG2DWO2  ...     1391731200   02 7, 2014
9997  A1GHQOXZME7VLL  1482012294  ...     1388880000   01 5, 2014
9998  A37ZXVSFNM1UAZ  1481978063  ...     1392076800  02 11, 2014
9999  A1EZD7IJOOAF6S  0956998569  ...     1402358400  06 10, 2014

[5 rows x 10 columns]

In [1469]:
Books_small.columns

Index(['reviewerID', 'asin', 'reviewerName', 'helpful/0', 'helpful/1',
       'reviewText', 'overall', 'summary', 'unixReviewTime', 'reviewTime'],
      dtype='object')

In [1470]:
Books_small.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   reviewerID      10000 non-null  object
 1   asin            10000 non-null  object
 2   reviewerName    9957 non-null   object
 3   helpful/0       10000 non-null  int64 
 4   helpful/1       10000 non-null  int64 
 5   reviewText      10000 non-null  object
 6   overall         10000 non-null  int64 
 7   summary         10000 non-null  object
 8   unixReviewTime  10000 non-null  int64 
 9   reviewTime      10000 non-null  object
dtypes: int64(4), object(6)
memory usage: 781.4+ KB


In [1471]:
Books_small.index

RangeIndex(start=0, stop=10000, step=1)

In [1472]:
Books_small.isnull()

reviewerID   asin  reviewerName  ...  summary  unixReviewTime  reviewTime
0          False  False         False  ...    False           False       False
1          False  False         False  ...    False           False       False
2          False  False         False  ...    False           False       False
3          False  False         False  ...    False           False       False
4          False  False         False  ...    False           False       False
...          ...    ...           ...  ...      ...             ...         ...
9995       False  False         False  ...    False           False       False
9996       False  False         False  ...    False           False       False
9997       False  False         False  ...    False           False       False
9998       False  False         False  ...    False           False       False
9999       False  False         False  ...    False           False       False

[10000 rows x 10 columns]

In [1473]:
Sentiments=[]
for num in Books_small['overall']:
  if num>4.0:
    Sentiments.append("Positive")
  else:
    Sentiments.append("Negative")
print(len(Sentiments))

10000


In [1474]:
data={'Ratings':Books_small['overall'],'Sentiments':Sentiments,'Customer Reviews':Books_small['reviewText']}
Target_Data=pd.DataFrame(data)
Target_Data.sample(5)

Ratings Sentiments                                   Customer Reviews
6152        5   Positive  Once again Stephen Leather keeps you turning t...
5738        4   Negative  This is one Finder's better books. It is thril...
9891        5   Positive  Very rarely do I follow a series one book at a...
3755        5   Positive  Great read filled with humor and a great messa...
4676        5   Positive  This is a very good read. So be sure to read t...

In [1475]:
training,test=train_test_split(Target_Data,test_size=0.33,random_state=42,stratify=Target_Data['Sentiments'])

In [1476]:
training.shape

(6700, 3)

In [1477]:
test.shape

(3300, 3)

In [1478]:
training

Ratings Sentiments                                   Customer Reviews
7205        1   Negative  I'm absolutely sick and tired of the man cheat...
6318        4   Negative  While Alice tries to &#8220;find herself&#8221...
6288        5   Positive  I found the stories contained in this set to b...
1042        5   Positive  Love the power these women portray and the hun...
4694        4   Negative  I like this book. It gives us a very healthy a...
...       ...        ...                                                ...
7465        5   Positive  I started my online journey in 2009 and basica...
9250        4   Negative  My mom read this book as a child.  It was her ...
2599        4   Negative  again Dan Gookin assistance is great for someo...
9597        5   Positive  This is a great read. The return to  Broslin C...
9163        5   Positive  While this is deemed to be the last of the tri...

[6700 rows x 3 columns]

In [1479]:
training['Customer Reviews'].iloc[3] #<---The Index Has Been Re-indexed When It Comes To iloc

'Love the power these women portray and the hunks that love them,'

In [1480]:
training['Sentiments'].iloc[3]

'Positive'

In [1481]:
training['Sentiments'].value_counts() # <---Data Is Biased

Positive    3973
Negative    2727
Name: Sentiments, dtype: int64

**BAG OF WORDS**

In [1482]:
train_x=training['Customer Reviews']
train_y=training['Sentiments']
test_x=test['Customer Reviews']
test_y=test['Sentiments']

In [1483]:
test_x.iloc[1]

"I really enjoyed this book. I couldn't put this book down until I finished it. The characters were good and the story line volume good."

In [1484]:
vectorizer = TfidfVectorizer()
train_xv = vectorizer.fit_transform(list(train_x))
test_xv=vectorizer.transform(list(test_x))
print(vectorizer.get_feature_names())

['00', '000', '00am', '00isbn', '01', '02', '03', '04', '0416', '07', '0758288956', '10', '100', '1000', '1001', '10032', '10084', '101', '102', '104', '105', '105s', '107', '10artwork', '10by', '10cool', '10overall', '10pm', '10th', '10value', '11', '115', '116', '1160', '1165', '118', '119', '11inches', '11n', '11year', '12', '120the', '122', '1239', '127775', '128', '128077', '128512', '128513', '128525', '12th', '12years', '13', '130', '1300', '132', '133', '134', '1344', '1375', '138', '139', '13th', '14', '140', '1402294150', '141992379x', '143', '1431', '1447', '1450', '14rate', '14th', '15', '150', '1500', '1500s', '1543', '1564', '157', '15th', '16', '160', '1600', '1603819592', '1632', '1633', '164', '1644', '1666', '168', '16th', '17', '1700', '1714', '175', '1765', '1770', '1779', '1785', '1793', '17th', '18', '1800', '1800s', '1812', '182', '1825', '1830', '1845', '1848', '1856', '1861', '1866', '1867', '1875', '1876', '1879', '1880', '1881', '1885', '1887', '1889', '189',

In [1485]:
train_xv.shape

(6700, 26663)

In [1486]:
test_xv.shape

(3300, 26663)

In [1487]:
train_y.value_counts()

Positive    3973
Negative    2727
Name: Sentiments, dtype: int64

**TESTING ON MULTIPLE CLASSIFICATION ALGORITHMS**

**LINEAR SVM**

In [1503]:
clf_svm=svm.SVC(kernel='linear')
clf_svm.fit(train_xv,train_y)
clf_svm.predict(test_xv[1])

array(['Positive'], dtype=object)

**DECISION TREE**

In [1489]:
clf_DecTree=DecisionTreeClassifier()
clf_DecTree.fit(train_xv,train_y)
clf_DecTree.predict(test_xv[1])

array(['Positive'], dtype=object)

**LOGISTIC REGRESSION**

In [1490]:
clf_log=LogisticRegression(max_iter=1000)
clf_log.fit(train_xv,train_y)
clf_log.predict(test_xv[1])

array(['Positive'], dtype=object)

**NAIVE BAYES**

In [1491]:
clf_gnb=GaussianNB()
clf_gnb.fit(train_xv.toarray(),train_y)
clf_gnb.predict(test_xv[1].toarray())

array(['Negative'], dtype='<U8')

**PERFORMANCE**

MEAN ACCURACY

In [1492]:
clf_svm.score(test_xv,test_y)

0.7306060606060606

In [1493]:
clf_DecTree.score(test_xv,test_y)

0.613030303030303

In [1494]:
clf_gnb.score(test_xv.toarray(),test_y)

0.5187878787878788

In [1495]:
clf_log.score(test_xv,test_y)

0.733030303030303

F-1 SCORE

In [1496]:
f1_score(test_y,clf_svm.predict(test_xv),average=None)

array([0.64482621, 0.78301196])

In [1497]:
f1_score(test_y,clf_DecTree.predict(test_xv),average=None)

array([0.52010522, 0.67580604])

In [1498]:
f1_score(test_y,clf_log.predict(test_xv),average=None)

array([0.63519669, 0.78948626])

In [1499]:
f1_score(test_y,clf_gnb.predict(test_xv.toarray()),average=None)

array([0.51761847, 0.51995163])

In [1509]:
example=['do not buy this bad book', ' love this Book','impressive book']
example=vectorizer.transform(example)
clf_svm.predict(example)

array(['Negative', 'Positive', 'Positive'], dtype=object)

**GRID SEARCH**

In [ ]:
vector_machine=svm.SVC()
parameters={'kernel':('rbf','linear'),'C':(1,2,3,6,7)}
clf=GridSearchCV(vector_machine,parameters,cv=5)
clf.fit(train_xv,train_y)